/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package src;

import java.awt.Color;
import java.awt.Font;
import java.lang.reflect.Array;

/**
 *
 * @author dangt
 */
public class test extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public test() {
        initComponents();
        jlbO.setEnabled(false);
        jlbX.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlbO = new javax.swing.JLabel();
        jlbX = new javax.swing.JLabel();
        jlb0 = new javax.swing.JLabel();
        jlb1 = new javax.swing.JLabel();
        jlb4 = new javax.swing.JLabel();
        jlb3 = new javax.swing.JLabel();
        jlb5 = new javax.swing.JLabel();
        jlb7 = new javax.swing.JLabel();
        jlb6 = new javax.swing.JLabel();
        jlb8 = new javax.swing.JLabel();
        jlb2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbO.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jlbO.setForeground(new java.awt.Color(0, 153, 0));
        jlbO.setText("O");
        jPanel1.add(jlbO, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 30, 40));

        jlbX.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jlbX.setForeground(new java.awt.Color(204, 0, 0));
        jlbX.setText("X");
        jPanel1.add(jlbX, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 30, 40));

        jlb0.setPreferredSize(new java.awt.Dimension(70, 70));
        jlb0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlb0MouseClicked(evt);
            }
        });
        jPanel1.add(jlb0, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        jlb1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlb1.setPreferredSize(new java.awt.Dimension(70, 70));
        jlb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlb1MouseClicked(evt);
            }
        });
        jPanel1.add(jlb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        jlb4.setPreferredSize(new java.awt.Dimension(70, 70));
        jlb4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlb4MouseClicked(evt);
            }
        });
        jPanel1.add(jlb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));

        jlb3.setPreferredSize(new java.awt.Dimension(70, 70));
        jlb3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlb3MouseClicked(evt);
            }
        });
        jPanel1.add(jlb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        jlb5.setPreferredSize(new java.awt.Dimension(70, 70));
        jlb5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlb5MouseClicked(evt);
            }
        });
        jPanel1.add(jlb5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        jlb7.setPreferredSize(new java.awt.Dimension(70, 70));
        jlb7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlb7MouseClicked(evt);
            }
        });
        jPanel1.add(jlb7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        jlb6.setPreferredSize(new java.awt.Dimension(70, 70));
        jlb6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlb6MouseClicked(evt);
            }
        });
        jPanel1.add(jlb6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

        jlb8.setPreferredSize(new java.awt.Dimension(70, 70));
        jlb8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlb8MouseClicked(evt);
            }
        });
        jPanel1.add(jlb8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, -1, -1));

        jlb2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlb2.setPreferredSize(new java.awt.Dimension(70, 70));
        jlb2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlb2MouseClicked(evt);
            }
        });
        jPanel1.add(jlb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 260, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, 250));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, 250));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 260, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public boolean flag = true;
    public int count = 0;
    
    public void checkTurn() {
        if(count==9) 
            jlbO.setEnabled(false);
            jlbX.setEnabled(false);
    }
    
    private void jlb0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlb0MouseClicked
        if(jlb0.getText().equals("")) {
            if (flag) {
                jlb0.setText(" X");
                jlb0.setForeground(Color.red);
                jlbO.setEnabled(true);
                jlbX.setEnabled(false);
                //
                jlb0.setFont(new Font("Tahoma", Font.PLAIN, 48));
            } else{
                jlb0.setText(" O");
                jlb0.setForeground(new Color(0,153,0));
                jlbX.setEnabled(true);
                jlbO.setEnabled(false);
                jlb0.setFont(new Font("Tahoma", Font.PLAIN, 48));
            }
            flag =! flag;
            checkTurn();
            count++;
        }
    }//GEN-LAST:event_jlb0MouseClicked

    private void jlb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlb1MouseClicked
        if(jlb1.getText().equals("")) {
            if (flag) {
                jlb1.setText(" X");
                jlb1.setFont(new Font("Tahoma", Font.PLAIN, 48));
                jlb1.setForeground(Color.red);
                jlbO.setEnabled(true);
                jlbX.setEnabled(false);
            } else{
                jlb1.setText(" O");
                jlb1.setFont(new Font("Tahoma", Font.PLAIN, 48));
                jlb1.setForeground(new Color(0,153,0));
                jlbO.setEnabled(false);
                jlbX.setEnabled(true);
            }
            flag =! flag;
            checkTurn();
            count++;
        }
    }//GEN-LAST:event_jlb1MouseClicked

    private void jlb3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlb3MouseClicked
        if(jlb3.getText().equals("")) {
            if (flag ) {
                jlb3.setText(" X");
                jlb3.setFont(new Font("Tahoma", Font.PLAIN, 48));
                jlb3.setForeground(Color.red);
                jlbO.setEnabled(true);
                jlbX.setEnabled(false);
            } else{
                jlb3.setText(" O");
                jlb3.setFont(new Font("Tahoma", Font.PLAIN, 48));
                jlb3.setForeground(new Color(0,153,0));
                jlbO.setEnabled(false);
                jlbX.setEnabled(true);
            }
            flag =! flag;
            checkTurn();
            count++;
        }
    }//GEN-LAST:event_jlb3MouseClicked

    private void jlb4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlb4MouseClicked
        if(jlb4.getText().equals("")) {
            if (flag ) {
                jlb4.setText(" X");
                jlb4.setFont(new Font("Tahoma", Font.PLAIN, 48));
                jlb4.setForeground(Color.red);
                jlbO.setEnabled(true);
                jlbX.setEnabled(false);
            } else{
                jlb4.setText(" O");
                jlb4.setFont(new Font("Tahoma", Font.PLAIN, 48));
                jlb4.setForeground(new Color(0,153,0));
                jlbO.setEnabled(false);
                jlbX.setEnabled(true);
            }
            flag =! flag;
            checkTurn();
            count++;
        }
    }//GEN-LAST:event_jlb4MouseClicked

    private void jlb5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlb5MouseClicked
        if(jlb5.getText().equals("")) {
            if (flag ) {
                jlb5.setText(" X");
                jlb5.setFont(new Font("Tahoma", Font.PLAIN, 48));
                jlb5.setForeground(Color.red);
                jlbO.setEnabled(true);
                jlbX.setEnabled(false);
            } else{
                jlb5.setText(" O");
                jlb5.setFont(new Font("Tahoma", Font.PLAIN, 48));
                jlb5.setForeground(new Color(0,153,0));
                jlbO.setEnabled(false);
                jlbX.setEnabled(true);
            }
            flag =! flag;
            checkTurn();
            count++;
        }
    }//GEN-LAST:event_jlb5MouseClicked

    private void jlb6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlb6MouseClicked
        if(jlb6.getText().equals("")) {
            if (flag ) {
                jlb6.setText(" X");
                jlb6.setFont(new Font("Tahoma", Font.PLAIN, 48));
                jlb6.setForeground(Color.red);
                jlbO.setEnabled(true);
                jlbX.setEnabled(false);
            } else{
                jlb6.setText(" O");
                jlb6.setFont(new Font("Tahoma", Font.PLAIN, 48));
                jlb6.setForeground(new Color(0,153,0));
                jlbO.setEnabled(false);
                jlbX.setEnabled(true);
            }
            flag =! flag;
            checkTurn();
            count++;
        }
    }//GEN-LAST:event_jlb6MouseClicked

    private void jlb7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlb7MouseClicked
        if(jlb7.getText().equals("")) {
            if (flag ) {
                jlb7.setText(" X");
                jlb7.setFont(new Font("Tahoma", Font.PLAIN, 48));
                jlb7.setForeground(Color.red);
                jlbO.setEnabled(true);
                jlbX.setEnabled(false);
            } else{
                jlb7.setText(" O");
                jlb7.setFont(new Font("Tahoma", Font.PLAIN, 48));
                jlb7.setForeground(new Color(0,153,0));
                jlbO.setEnabled(false);
                jlbX.setEnabled(true);
            }
            flag =! flag;
            checkTurn();
            count++;
        }
    }//GEN-LAST:event_jlb7MouseClicked

    private void jlb8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlb8MouseClicked
        if(jlb8.getText().equals("")) {
            if (flag ) {
                jlb8.setText(" X");
                jlb8.setFont(new Font("Tahoma", Font.PLAIN, 48));
                jlb8.setForeground(Color.red);
                jlbO.setEnabled(true);
                jlbX.setEnabled(false);
            } else{
                jlb8.setText(" O");
                jlb8.setFont(new Font("Tahoma", Font.PLAIN, 48));
                jlb8.setForeground(new Color(0,153,0));
                jlbO.setEnabled(false);
                jlbX.setEnabled(true);
            }
            flag =! flag;
            checkTurn();
            count++;
        }
    }//GEN-LAST:event_jlb8MouseClicked

    private void jlb2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlb2MouseClicked
        if(jlb2.getText().equals("")) {
            if (flag ) {
                jlb2.setText(" X");
                jlb2.setFont(new Font("Tahoma", Font.PLAIN, 48));
                jlb2.setForeground(Color.red);
                jlbO.setEnabled(true);
                jlbX.setEnabled(false);
            } else{
                jlb2.setText(" O");
                jlb2.setFont(new Font("Tahoma", Font.PLAIN, 48));
                jlb0.setForeground(new Color(0,153,0));
                jlbO.setEnabled(false);
                jlbX.setEnabled(true);
            }
            flag =! flag;
            checkTurn();
            count++;
        }
    }//GEN-LAST:event_jlb2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new test().setVisible(true);
            }
        });
    }
    
    
    public void getXO() {
        //if (flag) { //flag True X, false O
            //  button.innerText = flag ? "X" : "O";  
        //}
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jlb0;
    private javax.swing.JLabel jlb1;
    private javax.swing.JLabel jlb2;
    private javax.swing.JLabel jlb3;
    private javax.swing.JLabel jlb4;
    private javax.swing.JLabel jlb5;
    private javax.swing.JLabel jlb6;
    private javax.swing.JLabel jlb7;
    private javax.swing.JLabel jlb8;
    private javax.swing.JLabel jlbO;
    private javax.swing.JLabel jlbX;
    // End of variables declaration//GEN-END:variables
}
